const CartActionTypes = {
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  CLEAR_CART_ITEM: 'CLEAR_CART_ITEM',
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
};

export default CartActionTypes;
